application_display_name = "example-service-account"
role_name                = "example-service-account-role"
security_group_name      = "example-group"
GITHUB_REPOSITORY_OWNER  = "sim-parables"
GITHUB_REPOSITORY        = "sim-parables/terraform-azure-service-account"
GITHUB_REF               = "refs/heads/main"
GITHUB_ENV               = "production"