function_name           = "example-function-blob-trigger"
GITHUB_REPOSITORY_OWNER = "sim-parables"
GITHUB_REPOSITORY       = "sim-parables/terraform-azure-service-account"
GITHUB_REF              = "refs/heads/main"
GITHUB_ENV              = "production"